function [X,p]=RB_simulator...
                (X0,p0,FT,...
                  k,phi,reactant_vector,product_vector,...
                  follower_subsystems,truncated_size,...
                  reaction_decomposition_F,species_decomposition_LF,...
                  rowI,colI,reactionI,followerX,...
                  rowI_Jump,colI_Jump,reactionI_Jump,followerX_Jump,...
                  leader_subsystems_reactions,Leader_subsystems,...
                  A_update_or_not)

% this function use the RB method to simulate the process. 
% This algorithm returns the final state, and the final distribution

% SSA simulation 
   [t,X1]=next_reaction_method_single_trajectory...
               (X0,k,phi,FT,reactant_vector,product_vector);
   p=FFSP(t,X1,p0,k,phi,...
                follower_subsystems,truncated_size,...
                reaction_decomposition_F,species_decomposition_LF,...
                rowI,colI,reactionI,followerX,...
                rowI_Jump,colI_Jump,reactionI_Jump,followerX_Jump,...
                leader_subsystems_reactions,Leader_subsystems,...
                A_update_or_not);    
   X=X1(:,end);
   
           